-- MySQL Script generated by MySQL Workbench
-- 03/28/20 14:46:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `ID` VARCHAR(45) NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Usuario_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`, `Usuario_ID`),
  INDEX `fk_Cliente_Usuario_idx` (`Usuario_ID` ASC),
  CONSTRAINT `fk_Cliente_Usuario`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Usuario_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  INDEX `fk_Administrador_Usuario1_idx` (`Usuario_ID` ASC),
  CONSTRAINT `fk_Administrador_Usuario1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Restaurante` (
  `Idrestaurante` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Categoria` VARCHAR(45) NULL,
  `Zona` VARCHAR(45) NULL,
  `Tipo_servicio` VARCHAR(45) NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  PRIMARY KEY (`Idrestaurante`, `Administrador_idAdministrador`),
  INDEX `fk_Restaurante_Administrador1_idx` (`Administrador_idAdministrador` ASC),
  CONSTRAINT `fk_Restaurante_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `mydb`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `Cantidad` INT NULL,
  `Precio` DECIMAL(2) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Cliente_Usuario_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`, `Cliente_Usuario_ID`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC, `Cliente_Usuario_ID` ASC),
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente` , `Cliente_Usuario_ID`)
    REFERENCES `mydb`.`Cliente` (`idCliente` , `Usuario_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `idFactura` INT NOT NULL,
  `Precio` DECIMAL(2) NULL,
  `Cantidad` INT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`idFactura`, `Pedido_idPedido`),
  INDEX `fk_Factura_Pedido1_idx` (`Pedido_idPedido` ASC),
  CONSTRAINT `fk_Factura_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `idReserva` INT NOT NULL,
  `Fecha` DATE NULL,
  `Hora` DATETIME NULL,
  `Numeropersonas` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Cliente_Usuario_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReserva`, `Cliente_idCliente`, `Cliente_Usuario_ID`),
  INDEX `fk_Reserva_Cliente1_idx` (`Cliente_idCliente` ASC, `Cliente_Usuario_ID` ASC),
  CONSTRAINT `fk_Reserva_Cliente1`
    FOREIGN KEY (`Cliente_idCliente` , `Cliente_Usuario_ID`)
    REFERENCES `mydb`.`Cliente` (`idCliente` , `Usuario_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `idMenu` INT NOT NULL,
  `Nombrep` VARCHAR(45) NULL,
  `FechaValidez` VARCHAR(45) NULL,
  `Restaurante_Idrestaurante` INT NOT NULL,
  `Restaurante_Administrador_idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idMenu`, `Restaurante_Idrestaurante`, `Restaurante_Administrador_idAdministrador`),
  INDEX `fk_Menu_Restaurante1_idx` (`Restaurante_Idrestaurante` ASC, `Restaurante_Administrador_idAdministrador` ASC),
  CONSTRAINT `fk_Menu_Restaurante1`
    FOREIGN KEY (`Restaurante_Idrestaurante` , `Restaurante_Administrador_idAdministrador`)
    REFERENCES `mydb`.`Restaurante` (`Idrestaurante` , `Administrador_idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Oferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Oferta` (
  `idOferta` INT NOT NULL,
  `Nombre_publicidad` VARCHAR(45) NULL,
  `Costo` DECIMAL(2) NULL,
  `FechaInicio` DATE NULL,
  `FechaFin` DATE NULL,
  `Menu_idMenu` INT NOT NULL,
  `Menu_Restaurante_Idrestaurante` INT NOT NULL,
  `Menu_Restaurante_Administrador_idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idOferta`, `Menu_idMenu`, `Menu_Restaurante_Idrestaurante`, `Menu_Restaurante_Administrador_idAdministrador`),
  INDEX `fk_Oferta_Menu1_idx` (`Menu_idMenu` ASC, `Menu_Restaurante_Idrestaurante` ASC, `Menu_Restaurante_Administrador_idAdministrador` ASC),
  CONSTRAINT `fk_Oferta_Menu1`
    FOREIGN KEY (`Menu_idMenu` , `Menu_Restaurante_Idrestaurante` , `Menu_Restaurante_Administrador_idAdministrador`)
    REFERENCES `mydb`.`Menu` (`idMenu` , `Restaurante_Idrestaurante` , `Restaurante_Administrador_idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
